
<?php

/**
* **********************************************************************************************************************************
* MODULE API EMPLOI MONTPELLIER METROPOLE
* API "OFFRES D'EMPLOI V2"
* https://www.emploi-store-dev.fr/portail-developpeur-cms/home/catalogue-des-api/documentation-des-api/api/api-offres-demploi-v2.html
* API "MA BONNE BOITE V1"
* https://www.emploi-store-dev.fr/portail-developpeur-cms/home/catalogue-des-api/documentation-des-api/api/api-la-bonne-boite-v1.html
* **********************************************************************************************************************************
*/



/**
*************************************************************************************************************************************
 * I - CONFIGURATION DRUPAL
 ***********************************************************************************************************************************
 */

/**
 * Implementation of hook_help()
 * Définition du module dans Drupal
 */
function api_emploi_help($path, $arg) {
  switch ($path) {
    case 'admin/help#api_emploi':
      return '<p>' . t('Intégration de l\'API de pole emploi.') . '</p>';
  }
}


/*
 * Implementation of hook_menu()
 * Pages/routes du module
 */
function api_emploi_menu() {
  $items['api_emploi'] = array(
    'title' => 'API EMPLOI',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK, 
    'page callback' => 'api_emploi_content',
  );

  $items['api_emploi_query'] = array(
    'title' => 'API EMPLOI QUERY',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK, 
    'page callback' => 'api_emploi_query',
  );

  $items['api_emploi_result'] = array(
    'title' => 'Résultat de la recherche',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK, 
    'page callback' => 'api_emploi_result',
  );

  $items['api_emploi_one'] = array(
    'title' => 'Détails de l\'annonce',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK, 
    'page callback' => 'api_emploi_one',
  );

  $items['api_emploi_map'] = array(
    'title' => 'Widget Pole Emploi',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK, 
    'page callback' => 'api_emploi_map',
  );

  $items['api_emploi_total'] = array(
    'title' => 'API EMPLOI TOTAL',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK, 
    'page callback' => 'api_emploi_total',
  );

  $items['api_emploi_redirect'] = array(
    'title' => 'RESULTAT DE VOTRE RECHERCHE',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK, 
    'page callback' => 'api_emploi_redirect',
  );

  $items['api_emploi_lbb'] = array(
    'title' => 'La bonne boite',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK, 
    'page callback' => 'api_emploi_lbb',
  );

  $items['admin/config/system/api_emploi'] = array(
    'title' => t('Configuration de l\'API Pole emploi'),
    'description' => t('API EMPLOI configuration page'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('api_emploi_admin_settings'),
    'access arguments' => array('administrer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['api_emploi/formulaire'] = array(
    'title' => 'Rechercher une offre d\'emploi',
    'page callback' => 'api_emploi_form',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    );


  return $items; 
}

/*
 * Formulaire d'administration
 * Configuration du module dans la page d'administration 
 */
function api_emploi_admin_settings(){
  $form['api_emploi_module_user'] = array(
    '#type' => 'textfield',
    '#title' => t('Identifiant'),
    '#description' => t('identifiant de l\'utilisateur de l\'API Pole emploi'),
    '#default_value' => variable_get('api_emploi_module_user','Activated modules'), 
  );
  $form['api_emploi_module_secret'] = array(
    '#type' => 'textfield',
    '#title' => t('Secret key'),
    '#description' => t('clé secrète de l\'utilisateur de l\'API Pole emploi'),
    '#default_value' => variable_get('api_emploi_module_secret','Activated modules'), 
  );
  $form['api_emploi_module_token'] = array(
    '#type' => 'textfield',
    '#title' => t('URL token request'),
    '#description' => t('URL de la récupération du token de l\'API Pole emploi'),
    '#default_value' => variable_get('api_emploi_module_token','Activated modules'), 
  );
  $form['api_emploi_module_url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL api emploi'),
    '#description' => t('URL du module emploi de l\'API Pole emploi'),
    '#default_value' => variable_get('api_emploi_module_url','Activated modules'), 
  );

  $form['api_emploi_module_bb'] = array(
    '#type' => 'textfield',
    '#title' => t('URL La bonne boite'),
    '#description' => t('URL du module emploi de l\'API La bonne boite'),
    '#default_value' => variable_get('api_emploi_module_bb','Activated modules'), 
  );

  $form['api_emploi_module_limit'] = array(
    '#type' => 'textfield',
    '#title' => t('Limite d\'offre'),
    '#description' => t('Limite du nombre d\'offre d\'emploi' ),
    '#default_value' => variable_get('api_emploi_limit','30'), 
  );




  return system_settings_form($form);
}

/*
 * Les blocks de l'API EMPLOI
 */
function api_emploi_block_info() {
  $block['api_emploi_total'] = array(
    'info' => 'Offres d\'emploi métropole de montpellier',
  );

  $block['api_emploi_recherche'] = array(
    'info' => 'Rechercher une offre',
  );

  $block['api_lbb_recherche'] = array(
    'info' => 'Les secteurs qui recrutent',
  );

  return $block;
}

function api_emploi_block_view($delta) {

  switch ($delta) {
    case  'api_emploi_total':
      $block['subject'] = t('Nombre d\'offres d\'emploi sur la métropole de montpellier :');
      $block['content'] = '<h1>Total : ' . api_emploi_total() .  '</h1>';
      return $block;
      break;
    case  'api_emploi_resultat':
      $block['subject'] = t('Resulat de la recherche');
      $block['content'] = api_emploi_result();
      return $block;
      break;
    case  'api_emploi_recherche':
      $block['subject'] = t('Rechercher une offre');
      $block['content'] = api_emploi_query();
      return $block;
      break;
    case  'api_lbb_recherche':
      $block['subject'] = t('Les entreprises qui recrutent');
      $block['content'] = api_lbb_query();
      return $block;
      break;

}
}

/**
 * **********************************************************************************************************************************
 * RECUPERATION DU TOKEN & REQUETES POLE EMPLOI
 * Les informations de compte sont stockés dans la partie administration
 * **********************************************************************************************************************************
 */

/**
* creation des liens permettant d'obtenir le token d'accès à partir des informations de compte de l'utilisateur du site pole emploi
* $api = l'url de l'api correspondant (offre d'emploi (valeur 'oe') ou ma bonne boite (valeur 'bb'))
*/
function token_url_creator($api)
{
  $base_url = variable_get('api_emploi_module_token');
  $token_url = $base_url . "client_secret=" . variable_get('api_emploi_module_secret');
  $token_url .= "&client_id=" . variable_get('api_emploi_module_user') . "&grant_type=client_credentials&scope=";
    if($api == 'oe'){$token_url.= "application_" . variable_get('api_emploi_module_user') . "%20api_offresdemploiv2%20o2dsoffre&realm=/partenaire";}
    elseif($api == 'bb'){$token_url .= "application_" . variable_get('api_emploi_module_user') . "%20api_labonneboitev1&realm=/partenaire";}

  return $token_url;
}

/**
* Récupération du token sur le site de PE en fonction d'url de token_url_creator
*/
function getapitoken($url)
{
    $curl = curl_init();
    curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt_array($curl, array(
      CURLOPT_URL => $url,
      CURLOPT_RETURNTRANSFER => true,
      CURLOPT_ENCODING => '',
      CURLOPT_MAXREDIRS => 10,
      CURLOPT_TIMEOUT => 0,
      CURLOPT_FOLLOWLOCATION => true,
      CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
      CURLOPT_CUSTOMREQUEST => 'POST',
      CURLOPT_HTTPHEADER => array(
        'Content-Type: application/x-www-form-urlencoded',
      ),
    ));
    
    $response = curl_exec($curl);
    $err = curl_error($curl);
    curl_close($curl);
    $extract = json_decode($response, JSON_PRETTY_PRINT);


  return $extract['access_token'];
}




/**
* Extracteur de données JSON
* Convertion des données JSON en tableaux PHP
* API = Choix du type d'API ('oe' => offres d'emploi / 'bb' => bonne boite)
*/
function extract_Json($url, $api){


  $curl = curl_init();
  curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
  curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
  
  curl_setopt_array($curl, array(
    CURLOPT_URL => $url,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'GET',
    CURLOPT_HTTPHEADER => array(
      'Authorization: Bearer ' . getapitoken(token_url_creator($api))
    ),
  ));
  
  $response = curl_exec($curl);
  curl_close($curl);
  $extract = json_decode($response, JSON_PRETTY_PRINT);

  return $extract;
}

/**
 * **********************************************************************************************************************************
 * LISTES DES DONNEES
 * Liste des éléments pour la selection des choix dans les formulaires
 * **********************************************************************************************************************************
 */

/**
* Liste des villes de la metropole (Code INSEE de la commune )
*/
function liste_ville(){

  $ville = array(
    00000 => "Métropole de Montpellier",
    34022 => "Baillargues",
    34027 => "Beaulieu",
    34057 => "Castelnau-le-Lez",
    34058 => "Castries",
    34077 => "Clapiers",
    34087 => "Cournonsec",
    34088 => "Cournonterral",
    34095 => "Fabrègues",
    34116 => "Grabels",
    34120 => "Jacou",
    34123 => "Juvignac",
    34129 => "Lattes",
    34134 => "Lavérune",
    34090 => "Le Crès",
    34164 => "Montaud",
    34169 => "Montferrier-sur-Lez",
    34172 => "Montpellier",
    34179 => "Murviel-les-Montpellier",
    34198 => "Pérols",
    34202 => "Pignan",
    34217 => "Prades-le-Lez",
    34227 => "Restinclières",
    34244 => "Saint-Brès",
    34249 => "Saint-Drézéry",
    34256 => "Saint Geniès des Mourgues",
    34259 => "Saint Georges d'Orques",
    34270 => "Saint Jean de Védas",
    34295 => "Saussan",
    34307 => "Sussargues",
    34327 => "Vendargues",
    34337 => "Villeneuve-lès-Maguelone",
    );
   return $ville;
}

/**
* Liste des domaines (grandDomaine)
*/
function liste_domaines(){
  $domaines = array(
    "0" => "Tous domaines",
    "M" => "Achats / Comptabilité / Gestion",
    "A" => "Agriculture / Pêche / Espaces verts et naturels / Soins aux animaux",
    "B" => "Arts / Artisanat d’art",
    "C" => "Banque / Assurance",
    "F" => "Bâtiment / Travaux Publics",
    "D" => "Commerce / Vente",
    "E" => "Communication / Multimédia",
    "M14" => "Conseil/Etudes",
    "M13" => "Direction d’entreprise",
    "G" => "Hôtellerie – Restauration / Tourisme / Animation",
    "C15" => "Immobilier",
    "H" => "Industrie",
    "M18" => "Informatique / Télécommunication",
    "I" => "Installation / Maintenance",
    "M17" => "Marketing /Stratégie commerciale",
    "M15" => "Ressources Humaines",
    "J" => "Santé",
    "M16" => "Secrétariat/Assistanat",
    "K" => "Services à la personne / à la collectivité",
    "L" => "Spectacle",
    "L14" => "Sport",
    "N" => "Transport / Logistique",
  );

  return $domaines;
}

function liste_tri(){
  $tri = array(
    '0' => 'trier par pertinence',
    '1' => 'trier par date',
    '2' => 'trier par distance',
  );

  return $tri;
}

function liste_distance(){
  $distance = array(
    '0' => 'La ville seulement',
    '1' => '1km',
    '2' => '2km',
    '3' => '3km',
    '4' => '4km',
    '5' => '5km',
    '6' => '6km',
    '7' => '7km',
    '8' => '8km',
    '9' => '9km',
    '10' => '10km',
    '15' => '15km',
    '20' => '20km',
    '25' => '25km',
    '30' => '30km',
  );

  return $distance;
}

/**
 * **********************************************************************************************************************************
 * API OFFRE D'EMPLOI
 * Récupération des annonces du site de Pole Emploi
 * **********************************************************************************************************************************
 */

/**
* Création de l'URL de requete pour les recherches d'emploi
* Ville (code INSEE), domaine (Grand Domaine (liste))
*/
function url_request_creator(
  $ville = 'metropole', 
  $domaine = '', 
  $sort = 1,
  $distance = 5)
  {

      $url = array();
      $liste_domaines = liste_domaines();

      $base_url = variable_get('api_emploi_module_url');

      if($ville == 'metropole')
      {
        $criteres = 'commune=34172,34202,34058,34129,34123';
      }
      else
      {
        $source = 'api_emploi_result';
        if($ville != 0)
        {
          $criteres = 'commune=' . $ville;
          
        }
        else{
          $criteres = 'commune=34172,34202,34058,34129,34123';
        }
        
      }
      

      if(!empty($domaine)){
        $criteres .= "&grandDomaine=" . $domaine; 
        $query['domaine'] = $liste_domaines[$domaine];
      }


      $criteres .= "&distance=" . $distance; 
      $criteres .= "&sort=" . $sort; 
    
      $url_request  =  $base_url . $criteres;

      if(isset($_GET['page']))
      {
          $x = $_GET['page'] * 30;
          $y = $x + 30;
          $url_request  .= '&range=' . $x . '-' . $y;
      }      

      return $url_request = array(
        'url' => $url_request,
        'ville' => $ville,
        'domaine' => $domaine,
        'sort' => $sort,
        'distance' => $distance,

      );
}


/**
* Récupération des offres
*/
function getoffers($url, $page = 0)
{

  if(isset($_GET['page']))
  {
    $page = $_GET['page'];
    $url_query = $url['url'];
  }
  else
  {
    $url_query = $url['url'] . '&range=0-30';
  }

    $extract = extract_Json($url_query, 'oe');

  $communes = liste_ville();

    $query['offres'] = array();


    // Organisation du tableau des résultats => A mettre dans une fonction à part

    $compteur = 0;
      if(!empty($extract['resultats'])){
        foreach($extract['resultats'] as $o)
        {

          if(array_key_exists($o['lieuTravail']['commune'], $communes)){
            if(isset($o['entreprise']['nom']))
            {
              $offer = array(
                'id' => $o['id'],
                'titre' => $o['appellationlibelle'],
                'contrat' => $o['typeContrat'],
                'ville' => $o['lieuTravail']['libelle'],
                'description' => $o['description'],
                'date' => $o['dateCreation'],
                'entreprise' => $o['entreprise']['nom'],
                'lien' => 'https://candidat.pole-emploi.fr/offres/recherche/detail/' . $o['id'],
              );
            }
            else
            {
              $offer = array(
                'id' =>  $o['id'],        
                'titre' => $o['appellationlibelle'],
                'contrat' => $o['typeContrat'],
                'ville' => $o['lieuTravail']['libelle'],
                'description' => $o['description'],
                'date' => $o['dateCreation'],
                'entreprise' => '<em>non renseignée</em>',
                'lien' => 'https://candidat.pole-emploi.fr/offres/recherche/detail/' . $o['id'],
              ); 
            }
            array_push($query['offres'], $offer);
            $compteur++;

          }



        }

      $query['nombre'] = compter_emploi_ville($extract['filtresPossibles'][0]['agregation']);

      $villes = liste_ville();
      if(isset($url['ville']) and $url['ville'] != 'metropole'){
        $query['libelle_ville'] = $villes[$url['ville']];
      }

      if(isset($url['ville'])){
        $query['parameters'] = array(
          'ville' => $url['ville'],
          'domaine' => $url['domaine'],
          'sort' => $url['sort'],
          'distance' => $url['distance'],
          'nombre_offres' => $query['nombre'],
          'base_url' => current_path(),
        ); 
      }
      else{
        $query['parameters'] = array(
          'ville' => 'metropole',
          'domaine' => '',
          'sort' => '',
          'distance' => '',
          'nombre_offres' => $query['nombre'],
          'base_url' => current_path(),
        ); 
      }


      $query['pagination'] = api_navigation($query['parameters']);

    }

     return $query;
}




/*
 * url : /api_emploi
 * Page de base
 * Récupération des offres des plus grandes communes de la metropole (5 communes max par requete)
 */
function api_emploi_content() {
 
  $request = getoffers(url_request_creator()); //offres de montpellier par defaut

   return theme_api_emploi_paragraph($request);
}




/*
 * url : Création des pages de navigations dans les offres d'emplois
 */
function api_navigation($parameters) {


  $nombre = 30;
  $total = ceil($parameters['nombre_offres'] / $nombre);

  $navigation = array();
  $init = 0;

  $nav = $parameters['base_url'];

  if($parameters['base_url'] != 'api_emploi')
  {
    $nav .= '?ville=' . $parameters['ville'];
    $nav .= '&grandDomaine=' . $parameters['domaine'];
    $nav .= '&sort=' . $parameters['sort'];
    $nav .= '&distance=' . $parameters['sort'];
  }
  else{
    $nav .= '?ville=' . $parameters['ville'];
  }




  while($init < $total and $init < 34)
  {  
    $nav_url = $nav . '&page=' . $init;
    $init++;
    array_push($navigation, $nav_url);
  }


   return $navigation;
}


function api_emploi_one() {

 $url = 'https://api.emploi-store.fr/partenaire/offresdemploi/v2/offres/' . $_GET['id'];
 $extract = extract_Json($url, 'oe');

  return theme_api_emploi_one($extract);
}

function api_emploi_map(){

  $token = getapitoken(token_url_creator('oe'));

  $output = '';
  $output .= '<pe-offres-emploi></pe-offres-emploi>';
  $output .= '<script>';
  $output .= "var macarte=document.querySelector('pe-offres-emploi');";
  $output .= "macarte.options={rechercheAuto: false,},";
  $output .= 'macarte.token = "' . $token . '";';
  $output .= "</script>";

  return $output;
}
 /**
 * Affichage du resultat de la requete en liste
 */
function not_found() {

  $output = "Il n'y a aucune offre correspondant à ces critères : <br />";
  $villes = liste_ville();
  $domaine = liste_domaines();
  if($_GET['ville'] = 'metropole' or $_GET['ville'] = 0){
    $output .= 'Ville : Ensemble de la métropole de montpellier<br />';
  }
  else
  {
    $output .= "Ville : " . $villes[$_GET['ville']] . '<br />';
  }
  
  $output .= "Domaine : " . $domaine[$_GET['grandDomaine']] . '<br />';
  $output .= '<a href="api_emploi_query">Faire une nouvelle recherche</a>';

  return $output;
}


function api_emploi_total() {

  $total = get_total_offres_metropole();

  return $total;
}


/**
* Page d'affichage du résultat de la recherche
*/
function api_emploi_result() {

  if($_GET['ville'] == 0){$ville = "metropole";}else{$ville = $_GET['ville'];}
  if(isset($_GET['grandDomaine'])){$domaine = $_GET['grandDomaine'];}
  if(isset($_GET['sort'])){$sort = $_GET['sort'];}else{$sort = 1;}
  if(isset($_GET['distance'])){$distance = $_GET['distance'];}else{$distance = 4;}
  if(isset($_GET['page'])){$page = $_GET['page'];}else{$page=0;}

  $url = url_request_creator($ville, $domaine, $sort, $distance);

   
  $request = getoffers($url, $page);


  if(!empty($request['offres']))
  {
    
    if(!empty($request)){
      $content['nombre'] = compter_emploi_ville($request);
    }
    else{
      $content['nombre'] = 0;
    }
    return theme_api_emploi_paragraph($request);



  }
  else{
    return not_found();
  }



  ;
}

/**
* Navigation dans les pages d'affichage du résultat de la recherche
*/
function api_emploi_redirect(){

  if($_GET['ville'] == 0){$ville = "metropole";}else{$ville = $_GET['ville'];}
  if(isset($_GET['grandDomaine'])){$domaine = $_GET['grandDomaine'];}
  if(isset($_GET['sort'])){$sort = $_GET['sort'];}else{$sort = 1;}
  if(isset($_GET['distance'])){$distance = $_GET['distance'];}else{$distance = 0;}
  if(isset($_GET['page'])){$page = $_GET['page'];}else{$page=0;}
  $url = url_request_creator($ville, $domaine, $sort, $distance);

  $request = getoffers($url);


  if(!empty($request['offres']))
  {
    if(!empty($request)){
      $content['nombre'] = compter_emploi_ville($request);
    }
    else{
      $content['nombre'] = 0;
    }
   // return theme_api_emploi_paragraph($request);
  }
  else{
    return not_found();
  }
}

/**
*  * url : /api_emploi_query
* Page d'affichage du formulaire de recherche
*/
function api_emploi_query(){  
    return drupal_get_form('api_emploi_form');
}


/**
* Redirection vers la page des résultats après validation du formulaire
*/
function api_emploi_form_submit($form, &$form_state){
  $form_state['redirect'] = array('api_emploi_result',array('query' => array(
    'ville' => $form_state['values']['ville'], 
    'grandDomaine' => $form_state['values']['domaine'],
    'sort' => $form_state['values']['sort'],
    'distance' => $form_state['values']['distance'],
  )));
}



 /**
 * Formatage des offres en tableau
 */
function convert_table($o){

  $description = substr($o['description'],0,150);

  $url = '';
  if(isset($_GET['page'])){ $url .= '&page=' . $_GET['page']; }
  if(isset($_GET['ville'])){ $url .= '&ville=' . $_GET['ville']; }
  if(isset($_GET['grandDomaine'])){ $url .= '&grandDomaine=' . $_GET['grandDomaine']; }


  $pre_date = date_create($o['date']);
  $date = date_format($pre_date, 'd-m-Y');

  $output = "<tr>";
  $output .= "<td>" . $date . "</td>";
  $output .= "<td>" . $o['titre'] . "</td>";
  $output .= "<td>" . $o['ville'] . "</td>";
  $output .= "<td>" . $o['entreprise'] . "</td>";
  $output .= "<td>" . $description . " (...) </td>";
  $output .= '<td><a href="api_emploi_one?id=' . $o['id'] . $url .'">Voir l\'offre</a></td>';
  $output .= "</tr>";



  return $output;
}

/**
* Nombre d'offre pour une ville
*/
function compter_emploi_ville($extract){
  $total = 0;
  foreach($extract as $e){
    if(isset($e['nbResultats'])){
      $total = $total + $e['nbResultats'];
    }
  }
  return $total;
}

/**
* Calcul du nombre total d'offre d'emploi sur la metropole
*/
function get_total_offres_metropole(){

  $villes = liste_ville();


  $total = 0;
  foreach($villes as $k=>$v){
    $url = array();
    $url = variable_get('api_emploi_module_url') . "&commune=" . $k . "&distance=0&range=0-1";

    $extract = extract_Json($url, 'oe');

    if(!empty($extract['filtresPossibles'])){
      $total_ville = compter_emploi_ville($extract['filtresPossibles'][0]['agregation']);
      $total = $total + $total_ville;
    }
  }

  return $total; 
}

/**
* Formulaire de recherche
*/
function api_emploi_form(){
  $form['ville'] = array(
  '#title' => 'Choisir une ville de la métropole',
  '#type' => 'select',
  '#options' => liste_ville(),
  '#default_value' => array(34172 => "montpellier"),
  );

  $form['domaine'] = array(
    '#title' => 'Choisir un domaine d\'activité',
    '#type' => 'select',
    '#options' => liste_domaines(),
    '#default_value' => array(0 => "Tous domaines"),
    );

  $form['sort'] = array(
      '#title' => 'Tri des données',
      '#type' => 'select',
      '#options' => liste_tri(),
      '#default_value' => 1,
      );

  $form['distance'] = array(
        '#title' => 'Distance du rayon de recherche',
        '#type' => 'select',
        '#options' => liste_distance(),
        '#default_value' => 5,
        );
  
  $form['valider'] = array(
  '#type' => 'submit',
  '#value' => t('Soumettre'),
  );


  return $form;
}






/**
 * PARTIE TEMPLATE
 */


/**
 * Implementation of hook_theme
 */
function one_theme () {
  $functions = array(
    'one_offer' => array (
      'variables' => array('title' => NULL, 'content' => NULL)
    )
  );
  return $functions;
}

/**
 * Fonction de thème par défaut
 */
function theme_one_offer($variables) {
  $output = '<h4>'.$variable['title'].'</h4>';
  $output .= '<p>'.$variable['content'].'</p>';
  return $output;
}











/**
 * Affichage du resultat de la requete de toutes les offres de la metropole
 */
function theme_api_emploi_paragraph($variables) {

  if(!empty($variables['offres']))
  { 
    $output = '';

    if($variables['parameters']['base_url'] == 'api_emploi_result'){


      if($variables['parameters']['ville'] != 'metropole' and $variables['parameters']['ville'] != 0){
        $req_ville = $variables['libelle_ville'];
      }
      else
      {
        $req_ville = 'metropole de Montpellier';
      }

     
        $liste_domaines = liste_domaines();
        $req_domaine = $liste_domaines[$variables['parameters']['domaine']];

        $liste_distance = liste_distance();
        $req_distance = $liste_distance[$variables['parameters']['distance']];
        $liste_tri = liste_tri();
        $req_tri = $liste_tri[$variables['parameters']['sort']];


    
        $output .= '<h4>Votre recherche :</h4>';
        $output .=  '<ul>';
        $output .=  '<li>Ville : ' . $req_ville . '</li>';
        $output .=  '<li>Domaine : ' . $req_domaine . '</li>';
        $output .=  '<li>Trier par : ' . $req_tri . '</li>';
        $output .=  '<li>Air de recherche : ' . $req_distance . '</li>';
        $output .=  '<li>Résultat : <b>' . $variables['parameters']['nombre_offres'] . '</b></li>';
        $output .=  '</ul>';


    }


    if(isset($_GET['page'])){
      $page = $_GET['page'];
    }
    else{
      $page = 0;
    }


    if($variables['parameters']['nombre_offres'] > 30){
      $output .= '<ul>';
      $i = 0;
      foreach($variables['pagination'] as $p){
        $output .= '<li  style="display: inline; width = 5px;"><a href="'.$p .'"> ';
        if($i == $page){ $output .= ' <b>';  }
        $output .= $i;
        if($i == $page){ $output .= ' </b>';  }
        $output .= ' </a></li>';
        $i++;
      }
      $output .= '</ul>'; 
    }



  $output .= '<hr />'; 
  
    $output .= "<table>
    <tr>
            <th>Date</th>
            <th>Désignation</th>
            <th>Ville</th>
            <th>Entreprise</th>
            <th>Description</th>
            <th>Lien</th>
    </tr>";
    foreach($variables['offres'] as $o){
        $output .= convert_table($o);
    }

    $output .= "</table>";
    }
    else{
      $output = "Aucune offre dans ces critères";
    }


  return $output;
}




 /**
 * Affichage du resultat de la requete en tableau
 */
function theme_api_emploi_table($variables) {




  if(!empty($variables['offres']))
    {  
        $output = "";

		if(!isset($variables['domaine']) AND isset($variables['ville']))
		{
		  $output .= '<h5>Nombre d\'emploi sur la ville de ' . $variables['ville'] . ' : ' .$variables['nombre'] . '</h5>';
		}
		elseif(isset($variables['domaine']) AND !isset($variables['ville']))
		{
		$output .= '<h5>Nombre d\'emploi sur la metropole de montpellier dans le domaine ' . $variables['domaine'] . ' : ' .$variables['nombre'] . '</h5>';
		}
		else
		{
			$output .= '<h5>'.$variables['nombre']  . ' offres d\'emploi dans le domaine ' . $variables['domaine'] . ' à ' . $variables['ville'] .'</h5>';
		}

		
		if($variables['nombre'] > 30)
		{
			if(isset($_GET['page']))
			{
        $suivante = $x + 30;
        $precedent = $x - 30;
        if($_GET['page'] >= 30)
        {
          $output .= '<a href="api_emploi_result?ville='. $_GET['ville'] .'&grandDomaine='. $_GET['grandDomaine'] . '&page=0">Retour</a> | ';
          $output .= '<a href="api_emploi_result?ville='. $_GET['ville'] .'&grandDomaine='. $_GET['grandDomaine'] . '&page=' . $precedent . '">Page Précédente</a> | ';
        }
				
			}
			else
			{
				$suivante = $x + 30;
			}
      if($suivante <= $variables['nombre'])
      {
        $output .= '<a href="api_emploi_result?ville='. $_GET['ville'] .'&grandDomaine='. $_GET['grandDomaine'] . '&page=' . $suivante . '">Page Suivante</a>';
      }
			
			
		}
		$output .= '<p></p><a href="api_emploi_query">Nouvelle recherche</a></p>';
		
    }
    else
	{
      $output = "Aucune offre dans ces critères";
    }
    $output .= "<table>
    <tr>
            <th>ID</th>
            <th>Désignation</th>
            <th>Ville</th>
            <th>Entreprise</th>
            <th>Description</th>
            <th>Lien</th>
    </tr>";

    foreach($variables['offres'] as $o)
    {
        $output .= convert_table($o);
    }

    $output .= "</table>";
    
  return $output;
}










 /**
 * Affichage d'une offre
 */
function theme_api_emploi_one($offre)
{

  if(isset($_GET['grandDomaine']))
  {
    $domaine = $_GET['grandDomaine'];
  }
  else
  {
    $domaine = 0;
  }

  // url_creator : Permet de récupérer l'url de la page précédente
  // A FAIRE RAJOUTER SORT & DISTANCE PUIS VALEUR PAR DEFAUT
  if(!isset($_GET['ville']) && !isset($_GET['grandDomaine']))
  {
    $url_creator = "api_emploi";
    if(isset($_GET['page'])){ 
      $url_creator .= '?page=' . $_GET['page']; 
    }
  }
  else
  {
    $url_creator = 'api_emploi_result?&ville=' . $_GET['ville'] . '&grandDomaine=' . $domaine;
    if(isset($_GET['page'])){ 
      $url_creator .= '&page=' . $_GET['page']; 
    }
  }

  if(isset($_GET['sort'])){
    $url_creator .= '&sort=' . $_GET['sort'];
  }

  if(isset($_GET['distance'])){
    $url_creator .= '&distance=' . $_GET['distance'];
  }

  $token = getapitoken(token_url_creator('oe'));

  $output = '<h1>' . $offre['intitule'] . '</h1>';
  if(isset($offre['entreprise']['nom']))
  {
    $output .= '<h2>Entreprise : ' . $offre['entreprise']['nom'] .  '</h2>';
  }
  $output .= '<ul>';
  $date = date_create($offre['dateActualisation']);
  $output .= '<li>Date de l\'annonce : ' . date_format($date, 'd-m-Y') . '</li>';

  if(isset($offre['lieuTravail']))
  {
  $output .= '<li> Lieu de travail : ' . $offre['lieuTravail']['libelle'] . '</li>';
  }


  if(isset($offre['typeContrat']))
  {
  $output .= '<li>Type de contrat : ' . $offre['typeContrat'] . ' / ' . $offre['typeContratLibelle'] . '</li>';
  }


  if(isset($offre['dureeTravailLibelle'])){$output .= '<li>Durée de travail : ' . $offre['dureeTravailLibelle'] . '</li>';}
  $output .= '</ul>';
  $output .= '<a href="' . $url_creator . '">Retour</a> | ';
  $output .= '<a href="https://candidat.pole-emploi.fr/offres/recherche/detail/' .  $offre['id'] . '" target="_blank">Postulez sur le site de Pôle Emploi</a>';
  $output .= '<hr />';

  $output .= '<p>' . $offre['description'] .'</p>';
  $output .= '<hr />';


  if(isset($offre['lieuTravail']['latitude']) && isset($offre['lieuTravail']['longitude']))
  {
    $output .= '<iframe ';
    $output .=   'width="600"';
    $output .=   'height="400"';
    $output .=   'frameborder="0" style="border:0"';
    $output .=   'src="https://www.google.com/maps/embed/v1/place?key=AIzaSyB0X4kJMOTDHqCa9MJ6zSBTBJNET0opM4w';
    $output .=  '&center=' . $offre['lieuTravail']['latitude'] .  ',' . $offre['lieuTravail']['longitude'];
    $output .=  '&zoom=12';
    $output .=  '&q=' . $offre['lieuTravail']['libelle'];
    $output .= '" allowfullscreen>';
    $output .= '</iframe>';
  }



  return $output;
}





 /**
 * API LA BONNE BOITE POLE EMPLOI
 * 
 */

 /**
* creation du lien permettant d'obtenir le token d'accès à partir des informations de compte de l'utilisateur du site pole emploi
*/

function token_url_lbb_creator()
{

  $base_url = variable_get('api_emploi_module_token');
  $token_url = $base_url . "client_secret=" . variable_get('api_emploi_module_secret');
  $token_url = $token_url . "&client_id=" . variable_get('api_emploi_module_user') . "&grant_type=client_credentials&scope=";
  $token_url = $token_url . "application_" . variable_get('api_emploi_module_user') . "%20api_labonneboitev1&realm=/partenaire";

  return $token_url;
}


function token_url_rome_creator()
{

  $base_url = variable_get('api_emploi_module_token');
  $token_url = $base_url . "client_secret=" . variable_get('api_emploi_module_secret');
  $token_url = $token_url . "&client_id=" . variable_get('api_emploi_module_user') . "&grant_type=client_credentials&scope=";
  $token_url = $token_url . "application_" . variable_get('api_emploi_module_user') . "%20api_romev1&realm=/partenaire";

  return $token_url;
}


/**
*  * block : 
* Page d'affichage du formulaire de recherche
*/
function api_lbb_query()
{  
    return drupal_get_form('api_lbb_form');
}

function api_emploi_lbb(){
    
  if(!isset($_GET['page'])){
    $page = 1;
  }
  else{
    $page = $_GET['page'];
  };

  if(isset($_GET['metier']) && !empty($extract['companies']))
  {

    $content['text'] = "Votre recherche : " . $_GET['metier'];
    $url_lbb = "https://api.emploi-store.fr/partenaire/labonneboite/v1/company/?";
    $url = $url_lbb . 'commune_id=34172&rome_codes_keyword_search=' . $_GET['metier']  . '&page=' . $page;
    $extract = extract_lbb_Json($url);

    $entreprises = $extract['companies'];
    $content['nombre_entreprises'] = $extract['companies_count'];
    $content['code_rome'] = $extract['rome_code'];
    $content['code_label'] = $extract['rome_label'];
    $content['entreprises'] = array();

    $data['metier'] = $_GET['metier'];
    $data['page'] = $page;
    $data['total'] = $extract['companies_count'];
    $content['navigation'] = api_navigation_lbb($data);

    foreach($entreprises as $e){
      
      $value = array();
  
      $value['adresse'] = 'non renseigné';
      $value['contact_mode'] = 'non renseigné';
      $value['ville'] = 'non renseigné';
      $value['website'] = 'non renseigné';
      $value['web_lbb'] = 'non renseigné';
      $value['siret'] = 'non renseigné';

      if(isset($e['name'])){$value['nom'] = $e['name'];}else{$value['nom'] = 'non renseigné';}
      if(isset($e['addresse'])){$value['adresse'] = $e['addresse'];}else{$value['adresse'] = 'non renseigné';}
      if(isset($e['contact_mode'])){$value['type_contact'] = $e['contact_mode'];}else{$value['type_contact'] = 'non renseigné';}
      if(isset($e['city'])){$value['ville'] = $e['city'];}else{$value['ville'] = 'non renseignée';}
      if(isset($e['website'])){$value['website'] = $e['website'];}else{$value['website'] = 'non renseigné';}
      if(isset($e['headcount_text'])){$value['nombre_salarie'] = $e['headcount_text'];}else{$value['nombre_salarie'] = 'non renseigné';}
      if(isset($e['siret'])){$value['siret'] = $e['siret'];}else{$value['siret'] = 'non renseigné';}

      array_push($content['entreprises'], $value);

    }

    return theme_api_emploi_lbb($content);
  }
  elseif(empty($extract['companies'])  && isset($_GET['metier'])){
    return 'Pas de résultat, essayez une nouvelle recherche';

  }

  return 'Recherchez un secteur qui recrute';
  
}


function theme_api_emploi_lbb($content){


  $output = '';

  $output .= '<h4>Votre recherche : ' . $_GET['metier'] . '</h4>';

  $output .= '<ul>';

  $output .= '<li>Code Rome : ' .$content['code_rome']. '</li>'; 
  
  $output .= '<li>Désignation : ' .$content['code_label']. '</li>';
  
  $output .= '<li>Nombre d\'entreprises: ' .$content['nombre_entreprises']. '</li>';  

  if(isset($_GET['page']))
  {
    $page = $_GET['page'];
  }
  else
  {
    $page = 1;
  }


  if($content['nombre_entreprises']  > 20){
    $output .= '<ul>';
    $i = 1;
    foreach($content['navigation'] as $p){
      $output .= '<li  style="display: inline; width = 5px;"><a href="'.$p .'"> ';
      if($i == $page){ $output .= ' <b>';  }
      $output .= $i;
      if($i == $page){ $output .= ' </b>';  }
      $output .= ' </a></li>';

      $i++;
    }
    $output .= '</ul>'; 
  }


  $output .= '<hr />'; 

  $output .= "<table>
  <tr>
          <th>Nom</th>
          <th>Ville</th>
          <th>Nombre de salariés</th>
          <th>Adresse</th>
          <th>Lien</th>
  </tr>";


  foreach($content['entreprises'] as $e){
    

    $output .= "<tr>";
    $output  .= "<td>" . $e['nom'] . "</td>";
    $output  .= "<td>" . $e['ville'] . "</td>";
    $output .= "<td>" . $e['nombre_salarie'] . "</td>";
    $output .= "<td>" . $e['adresse'] . "</td>";
    $output .= "<td>" . $e['website'] . "</td>";
    $output  .= "</tr>";

  }

  $output .= "</table>";



return $output;


}


/**
* Extracteur de données JSON
*/
function extract_lbb_Json($url){
  $curl = curl_init();
  curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
  curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
  
  curl_setopt_array($curl, array(
    CURLOPT_URL => $url,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'GET',
    CURLOPT_HTTPHEADER => array(
      'Authorization: Bearer ' . getapilbbtoken()
    ),
  ));
  
  $response = curl_exec($curl);
  curl_close($curl);
  $extract = json_decode($response, JSON_PRETTY_PRINT);

  return $extract;
}


/**
* Récupération du token sur le site de PE
*/
function getapilbbtoken()
{
  $url = token_url_lbb_creator();
  $curl = curl_init();
  curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
  curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
  curl_setopt_array($curl, array(
    CURLOPT_URL => $url,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'POST',
    CURLOPT_HTTPHEADER => array(
      'Content-Type: application/x-www-form-urlencoded',
    ),
  ));
  
  $response = curl_exec($curl);
  $err = curl_error($curl);
  curl_close($curl);
  $extract = json_decode($response, JSON_PRETTY_PRINT);

  return $extract['access_token'];   

}



/**
* Formulaire de recherche
*/
function api_lbb_form(){
  $form['metier'] = array(
  '#title' => 'Rechercher un métier ou secteur d\'activité',
  '#type' => 'textfield',
  );

  
  $form['valider'] = array(
  '#type' => 'submit',
  '#value' => t('Soumettre'),
  );


  return $form;
}

/**
* Redirection vers la page des résultats après validation du formulaire
*/
function api_lbb_form_submit($form, &$form_state){
  $form_state['redirect'] = array('api_emploi_lbb',array('query' => array(
    'metier' => $form_state['values']['metier'], 
  )));
}


/*
 * url : Création des pages de navigations dans les offres d'emplois
 */
function api_navigation_lbb($parameters) {


  $nombre = 20;
  $total = ceil($parameters['total'] / $nombre);

  $navigation = array();
  $init = 1;

  $nav = 'api_emploi_lbb';



  $nav .= '?metier=' . $parameters['metier'];


  while($init < $total and $init < 34)
  {  
    $nav_url = $nav . '&page=' . $init;
    $init++;
    array_push($navigation, $nav_url);
  }


   return $navigation;
}