
<?php

/**
* **********************************************************************************************************************************
* MODULE API EMPLOI MONTPELLIER METROPOLE
* API "OFFRES D'EMPLOI V2"
* https://www.emploi-store-dev.fr/portail-developpeur-cms/home/catalogue-des-api/documentation-des-api/api/api-offres-demploi-v2.html
* API "MA BONNE BOITE V1"
* https://www.emploi-store-dev.fr/portail-developpeur-cms/home/catalogue-des-api/documentation-des-api/api/api-la-bonne-boite-v1.html
* **********************************************************************************************************************************
*/



/**
*************************************************************************************************************************************
 * I - CONFIGURATION DRUPAL
 ***********************************************************************************************************************************
 */

/**
 * Implementation of hook_help()
 * Définition du module dans Drupal
 */
function api_emploi_help($path, $arg) {
  switch ($path) {
    case 'admin/help#api_emploi':
      return '<p>' . t('Intégration de l\'API de pole emploi.') . '</p>';
  }
}


/*
 * Implementation of hook_menu()
 * Pages/routes du module
 */
function api_emploi_menu() {
  $items['offres-emploi-metropole'] = array(
    'title' => 'Offres d’emploi Métropole Montpellier',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK, 
    'page callback' => 'api_emploi_content',
  );

  $items['api_emploi_query'] = array(
    'title' => 'API EMPLOI QUERY',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK, 
    'page callback' => 'api_emploi_query',
  );

  $items['offres-emploi'] = array(
    'title' => 'Offres d\'emploi',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK, 
    'page callback' => 'api_emploi_result',
  );

  $items['offres-emploi-saisonnier'] = array(
    'title' => 'Offres d\'emploi saisonniers',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK, 
    'page callback' => 'api_emploi_saisonnier',
  );

  $items['offres-alternance'] = array(
    'title' => 'Offres en alternance',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK, 
    'page callback' => 'api_emploi_formation',
  );

  $items['offre-emploi'] = array(
    'title' => 'Détails de l\'offre',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK, 
    'page callback' => 'api_emploi_one',
  );

  $items['api_emploi_total'] = array(
    'title' => 'API EMPLOI TOTAL',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK, 
    'page callback' => 'api_emploi_total',
  );


  $items['admin/config/system/api_emploi'] = array(
    'title' => t('Configuration de l\'API Pole emploi'),
    'description' => t('API EMPLOI configuration page'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('api_emploi_admin_settings'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['api_emploi/formulaire'] = array(
    'title' => 'Rechercher une offre d\'emploi',
    'page callback' => 'api_emploi_form',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    );



  return $items; 
}

/*
 * Formulaire d'administration
 * Configuration du module dans la page d'administration 
 */
function api_emploi_admin_settings(){
  $form['api_emploi_module_user'] = array(
    '#type' => 'textfield',
    '#title' => t('Identifiant'),
    '#description' => t('identifiant de l\'utilisateur de l\'API Pole emploi'),
    '#default_value' => variable_get('api_emploi_module_user','Activated modules'), 
  );
  $form['api_emploi_module_secret'] = array(
    '#type' => 'textfield',
    '#title' => t('Secret key'),
    '#description' => t('clé secrète de l\'utilisateur de l\'API Pole emploi'),
    '#default_value' => variable_get('api_emploi_module_secret','Activated modules'), 
  );
  $form['api_emploi_module_token'] = array(
    '#type' => 'textfield',
    '#title' => t('URL token request'),
    '#description' => t('URL de la récupération du token de l\'API Pole emploi'),
    '#default_value' => variable_get('api_emploi_module_token','Activated modules'), 
  );
  $form['api_emploi_module_url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL api emploi'),
    '#description' => t('URL du module emploi de l\'API Pole emploi'),
    '#default_value' => variable_get('api_emploi_module_url','Activated modules'), 
  );

  $form['api_emploi_module_limit'] = array(
    '#type' => 'textfield',
    '#title' => t('Limite d\'offre'),
    '#description' => t('Limite du nombre d\'offre d\'emploi' ),
    '#default_value' => variable_get('api_emploi_limit','30'), 
  );

  return system_settings_form($form);
}

/*
 * Les blocks de l'API EMPLOI
 */
function api_emploi_block_info() {
  $block['api_emploi_total'] = array(
    'info' => 'Offres d\'emploi métropole de montpellier',
  );

  $block['api_emploi_recherche'] = array(
    'info' => 'Rechercher une offre',
  );

  $block['api_emploi_resultat'] = array(
    'info' => 'Résultat de la recherche',
  );

  return $block;
}

function api_emploi_block_view($delta) {

  switch ($delta) {
    case  'api_emploi_total':
      $block['subject'] = t('Nombre d\'offres d\'emploi sur la métropole de montpellier :');
      $block['content'] = '<div class="api-pe-compteur"><div class="api-pe-compteur-before">Il y a actuellement</div>';
	  $block['content'] .= '<div class="api-pe-compteur-compteur">' . api_emploi_total() . '</div>';
	  $block['content'] .= '<div class="api-pe-compteur-after">offres d\'emploi sur le territoire de Montpellier Méditerranée Métropole</div>';
	  $block['content'] .= '</div>';
      return $block;
      break;
    case  'api_emploi_resultat':
      $block['subject'] = t('Resulat de la recherche');
      $block['content'] = api_emploi_result();
      return $block;
      break;
    case  'api_emploi_recherche':
      $block['subject'] = t('Rechercher une offre');
      $block['content'] = api_emploi_query();
      return $block;
      break;

}
}

/**
 * **********************************************************************************************************************************
 * RECUPERATION DU TOKEN & REQUETES POLE EMPLOI
 * Les informations de compte sont stockés dans la partie administration
 * **********************************************************************************************************************************
 */

/**
* creation des liens permettant d'obtenir le token d'accès à partir des informations de compte de l'utilisateur du site pole emploi
*/
function token_url_creator()
{
  $base_url = variable_get('api_emploi_module_token');
  $token_url = $base_url . "client_secret=" . variable_get('api_emploi_module_secret');
  $token_url .= "&client_id=" . variable_get('api_emploi_module_user') . "&grant_type=client_credentials&scope=";
  $token_url.= "application_" . variable_get('api_emploi_module_user') . "%20api_offresdemploiv2%20o2dsoffre&realm=/partenaire";

  return $token_url;
}

/**
* Récupération du token sur le site de PE en fonction d'url de token_url_creator
*/
function getapitoken($url)
{
    $curl = curl_init();
    curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt_array($curl, array(
      CURLOPT_URL => $url,
      CURLOPT_RETURNTRANSFER => true,
      CURLOPT_ENCODING => '',
      CURLOPT_MAXREDIRS => 10,
      CURLOPT_TIMEOUT => 0,
      CURLOPT_FOLLOWLOCATION => true,
      CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
      CURLOPT_CUSTOMREQUEST => 'POST',
      CURLOPT_HTTPHEADER => array(
        'Content-Type: application/x-www-form-urlencoded',
      ),
    ));
    
    $response = curl_exec($curl);
    $err = curl_error($curl);
    curl_close($curl);
    $extract = json_decode($response, JSON_PRETTY_PRINT);


  return $extract['access_token'];
}




/**
* Extracteur de données JSON
* Convertion des données JSON en tableaux PHP
*/
function extract_Json($url){


  $curl = curl_init();
  curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
  curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
  
  curl_setopt_array($curl, array(
    CURLOPT_URL => $url,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'GET',
    CURLOPT_HTTPHEADER => array(
      'Authorization: Bearer ' . getapitoken(token_url_creator())
    ),
  ));
  
  $response = curl_exec($curl);
  curl_close($curl);
  $extract = json_decode($response, JSON_PRETTY_PRINT);

  return $extract;
}

/**
 * **********************************************************************************************************************************
 * LISTES DES DONNEES
 * Liste des éléments pour la selection des choix dans les formulaires
 * **********************************************************************************************************************************
 */

/**
* Liste des villes de la metropole (Code INSEE de la commune )
*/
function liste_ville(){

  $ville = array(
    0 => "Métropole de Montpellier",
    34022 => "Baillargues",
    34027 => "Beaulieu",
    34057 => "Castelnau-le-Lez",
    34058 => "Castries",
    34077 => "Clapiers",
    34087 => "Cournonsec",
    34088 => "Cournonterral",
    34095 => "Fabrègues",
    34116 => "Grabels",
    34120 => "Jacou",
    34123 => "Juvignac",
    34129 => "Lattes",
    34134 => "Lavérune",
    34090 => "Le Crès",
    34164 => "Montaud",
    34169 => "Montferrier-sur-Lez",
    34172 => "Montpellier",
    34179 => "Murviel-les-Montpellier",
    34198 => "Pérols",
    34202 => "Pignan",
    34217 => "Prades-le-Lez",
    34227 => "Restinclières",
    34244 => "Saint-Brès",
    34249 => "Saint-Drézéry",
    34256 => "Saint Geniès des Mourgues",
    34259 => "Saint Georges d'Orques",
    34270 => "Saint Jean de Védas",
    34295 => "Saussan",
    34307 => "Sussargues",
    34327 => "Vendargues",
    34337 => "Villeneuve-lès-Maguelone",
    );
   return $ville;
}

/**
* Liste des domaines (grandDomaine)
*/
function liste_domaines(){
  $domaines = array(
    "0" => "Tous domaines",
    "M" => "Achats / Comptabilité / Gestion",
    "A" => "Agriculture / Pêche / Espaces verts et naturels / Soins aux animaux",
    "B" => "Arts / Artisanat d’art",
    "C" => "Banque / Assurance",
    "F" => "Bâtiment / Travaux Publics",
    "D" => "Commerce / Vente",
    "E" => "Communication / Multimédia",
    "M14" => "Conseil/Etudes",
    "M13" => "Direction d’entreprise",
    "G" => "Hôtellerie – Restauration / Tourisme / Animation",
    "C15" => "Immobilier",
    "H" => "Industrie",
    "M18" => "Informatique / Télécommunication",
    "I" => "Installation / Maintenance",
    "M17" => "Marketing /Stratégie commerciale",
    "M15" => "Ressources Humaines",
    "J" => "Santé",
    "M16" => "Secrétariat/Assistanat",
    "K" => "Services à la personne / à la collectivité",
    "L" => "Spectacle",
    "L14" => "Sport",
    "N" => "Transport / Logistique",
  );

  return $domaines;
}

function liste_tri(){
  $tri = array(
    '0' => 'trier par pertinence',
    '1' => 'trier par date',
    '2' => 'trier par distance',
  );

  return $tri;
}

function liste_distance(){
  $distance = array(
    '0' => 'La ville seulement',
    '1' => '1km',
    '2' => '2km',
    '3' => '3km',
    '4' => '4km',
    '5' => '5km',
    '6' => '6km',
    '7' => '7km',
    '8' => '8km',
    '9' => '9km',
    '10' => '10km',
    '15' => '15km',
    '20' => '20km',
    '25' => '25km',
    '30' => '30km',
  );

  return $distance;
}


function liste_contrat(){
  $contrat = array(
    '0' => 'Toutes les offres',
    'CDI' => 'Contrat à durée indéterminée',
    'CDD' => 'Contrat à durée déterminée',
    'MIS' => 'Mission Intérimaire',
    'SAI' => 'Saisonnier',
    'FS' => 'Contrat de professionnalisation',
    'E2' => 'Contrat d\'apprentissage',
    
  );
  return $contrat;
}

function liste_duree(){
  $duree = array(
    'X' => 'Toutes les offres',
    'true' => 'Temps plein',
    'false' => 'Temps partiel',
  );
  return $duree;
}

function liste_experience(){
  $experience = array(
    '0' => 'Toutes les offres',
    '1' => '1 an',
    '2' => '1 à 3 ans',
    '3' => 'Plus de 3 ans',
  );
  return $experience;
}

function liste_qualification(){
  $experience = array(
    '1' => 'Toutes les offres',
    '9' => 'Cadre',
    '0' => 'Non cadre',
  );
  return $experience;
}

function liste_date(){
  $date = array(
    '0' => 'Toutes les offres',
    '1' => '1 jour',
    '3' => '3 jours',
    '7' => '1 semaine',
    '14' => '2 semaine',
    '31' => '1 mois',
  );
  return $date;
}

/**
 * **********************************************************************************************************************************
 * API OFFRE D'EMPLOI
 * Récupération des annonces du site de Pole Emploi
 * **********************************************************************************************************************************
 */
/**
* Formulaire de recherche
*/
function api_emploi_form(){

  if(isset($_GET['ville'])){$ville = $_GET['ville'];}else{$ville = 0;}

  $form['ville'] = array(
  '#title' => 'Choisir une ville de la métropole',
  '#type' => 'select',
  '#options' => liste_ville(),
  '#default_value' => $ville,
  );

  if(isset($_GET['grandDomaine'])){$default_grandDomaine = $_GET['grandDomaine'];}else{$default_grandDomaine = 0;}

  $form['domaine'] = array(
  '#title' => 'Choisir un domaine d\'activité',
  '#type' => 'select',
  '#options' => liste_domaines(),
  '#default_value' => $default_grandDomaine,
  );

  if(isset($_GET['sort'])){$default_sort = $_GET['sort'];}else{$default_sort = 1;}

  $form['sort'] = array(
  '#title' => 'Tri des données',
  '#type' => 'select',
  '#options' => liste_tri(),
  '#default_value' => $default_sort,
  );

  if(isset($_GET['distance'])){$default_distance = $_GET['distance'];}else{$default_distance = 5;}
  $form['distance'] = array(
  '#title' => 'Distance du rayon de recherche',
  '#type' => 'select',
  '#options' => liste_distance(),
  '#default_value' => $default_distance,
  );

  if(isset($_GET['typeContrat'])){$default_typeContrat = $_GET['typeContrat'];}else{$default_typeContrat = 0;}

  $form['contrat'] = array(
  '#title' => 'Choisir un type de contrat',
  '#type' => 'select',
  '#options' => liste_contrat(),
  '#default_value' => $default_typeContrat,
  );
  
  if(isset($_GET['tempsPlein'])){$default_tempsPlein = $_GET['tempsPlein'];}else{$default_tempsPlein = 0;} 

  $form['duree'] = array(
  '#title' => 'Choisir une durée hebdomadaire',
  '#type' => 'select',
  '#options' => liste_duree(),
  '#default_value' => array(0 => $default_tempsPlein),
  );
     
  if(isset($_GET['experience'])){$default_experience = $_GET['experience'];}else{$default_experience = 4;}   
  $form['experience'] = array(
  '#title' => 'Expérience souhaitée',
  '#type' => 'select',
  '#options' => liste_experience(),
  '#default_value' => $default_experience,
  );
    
  if(isset($_GET['qualification'])){$default_qualification = $_GET['qualification'];}else{$default_qualification = 1;} 
  $form['qualification'] = array(
  '#title' => 'Niveau de qualification',
  '#type' => 'select',
  '#options' => liste_qualification(),
  '#default_value' => $default_qualification,
  );

  if(isset($_GET['publieeDepuis'])){$default_publieeDepuis = $_GET['publieeDepuis'];}else{$default_publieeDepuis = 0;}
  $form['date'] = array(
  '#title' => 'Date de publication',
  '#type' => 'select',
  '#options' => liste_date(),
  '#default_value' => $default_publieeDepuis,
  );
  
  $form['valider'] = array(
  '#type' => 'submit',
  '#value' => t('Rechercher'),
  );


  return $form;
}

/**
*  * url : /api_emploi_query
* Page d'affichage du formulaire de recherche
*/
function api_emploi_query(){  


  return drupal_get_form('api_emploi_form');
}

/**
* Récupération des éléments du formulaire
*/
function api_emploi_form_submit($form, &$form_state){
  $form_state['redirect'] = array('offres-emploi',array('query' => array(
    'ville' => $form_state['values']['ville'], 
    'grandDomaine' => $form_state['values']['domaine'],
    'sort' => $form_state['values']['sort'],
    'distance' => $form_state['values']['distance'],
    'typeContrat' => $form_state['values']['contrat'],
    'tempsPlein' => $form_state['values']['duree'],
    'experience' => $form_state['values']['experience'],
    'qualification' => $form_state['values']['qualification'],
    'publieeDepuis' => $form_state['values']['date'],
  )));

}



/**
* Création de l'URL de requete pour les recherches d'emploi
* Ville (code INSEE), domaine (Grand Domaine (liste))
*/
function url_request_creator(
  $ville = 0, 
  $domaine = '0', 
  $sort = 1,
  $distance = 20, 
  $typeContrat = '0', 
  $tempsPlein = 'X', 
  $experience = 0, 
  $qualification = 1, 
  $publieeDepuis = 0)
  {

      $url = array();
      $liste_domaines = liste_domaines();

      $base_url = variable_get('api_emploi_module_url');

      if($ville == 0)
      {
        $criteres = 'commune=34172&distance=25';
      }
      else
      {
        $source = 'offres-emploi';
        if($ville != 0)
        {
          $criteres = 'commune=' . $ville;
          $criteres .= "&distance=" . $distance;
          
        }
        else{
          $criteres = 'commune=34172&distance=25';
        }
        
      }
      

      if(!empty($domaine)){
        $criteres .= "&grandDomaine=" . $domaine; 
        $query['domaine'] = $liste_domaines[$domaine];
      }

      if($typeContrat != '0'){
        if($typeContrat == 'FS' or $typeContrat == 'E2'){
          $criteres .= "&natureContrat=" . $typeContrat;}
        elseif($typeContrat == 'forma')
        {
          $criteres .= "&natureContrat=FS,E2";
        }
        else{   
          $criteres .= "&typeContrat=" . $typeContrat;}
      }
      
      if($tempsPlein != 'X'){
          $criteres .= "&tempsPlein=" . $tempsPlein;
      } 
      
      if($experience != 0){
        $criteres .= "&experience=" . $experience;
      }

      if($qualification != 1){
        $criteres .= "&qualification=" . $qualification;
      }

      if($publieeDepuis != 0){
        $criteres .= "&publieeDepuis=" . $publieeDepuis;
      }

       
      $criteres .= "&sort=" . $sort; 
    
      $url_request  =  $base_url . $criteres;

      if(isset($_GET['page']))
      {
          $x = $_GET['page'] * 30;
          $y = $x + 30;
          $url_request  .= '&range=' . $x . '-' . $y;
      }      


      return $url_request = array(
        'url' => $url_request,
        'ville' => $ville,
        'domaine' => $domaine,
        'sort' => $sort,
        'distance' => $distance,
        'typeContrat' => $typeContrat,
        'tempsPlein' => $tempsPlein,
        'experience' => $experience,
        'qualification' => $qualification,
        'publieeDepuis' => $publieeDepuis,
      );
}


/**
* Récupération des offres
*/
function getoffers($url, $page = 0)
{

  if(isset($_GET['page']))
  {
    $page = $_GET['page'];
    $url_query = $url['url'];
  }
  else
  {
    $url_query = $url['url'] . '&range=0-30';
  }

    $extract = extract_Json($url_query);

    $communes = liste_ville();

    $query['offres'] = array();


    // Organisation du tableau des résultats => A mettre dans une fonction à part

    $compteur = 0;
      if(!empty($extract['resultats'])){
        foreach($extract['resultats'] as $o)
        {

          // PERMET DE FILTER LES VILLES HORS METROPOLE -> A commenter si obsolète
       //   if(array_key_exists($o['lieuTravail']['commune'], $communes)){

            $offer = extractOffer($o);
            array_push($query['offres'], $offer);
            $compteur++;

      //    }



        }

      $query['nombre'] = compter_emploi_ville($extract['filtresPossibles'][0]['agregation']);

      $villes = liste_ville();
      if(isset($url['ville']) and $url['ville'] != 0){
        $query['libelle_ville'] = $villes[$url['ville']];
      }

      if(isset($url['ville'])){
        $query['parameters'] = array(
          'ville' => $url['ville'],
          'domaine' => $url['domaine'],
          'sort' => $url['sort'],
          'distance' => $url['distance'],
          'typeContrat' => $url['typeContrat'],
          'tempsPlein' => $url['tempsPlein'],
          'experience' => $url['experience'],
          'qualification' => $url['qualification'],
          'publieeDepuis' => $url['publieeDepuis'],
          'nombre_offres' => $query['nombre'],
          'base_url' => current_path(),
        ); 
      }
      else{
        $query['parameters'] = array(
          'ville' => 'metropole',
          'domaine' => '',
          'sort' => '',
          'distance' => '',
          'nombre_offres' => $query['nombre'],
          'base_url' => current_path(),
        ); 
      }


      $query['pagination'] = api_navigation($query['parameters']);

    }

     return $query;
}

function extractOffer($offre)
{


  if(isset($offre['intitule'])){$intitule = $offre['intitule'];}else{$intitule = '';}
  if(isset($offre['dateCreation'])){$dateCreation = $offre['dateCreation'];}else{$dateCreation = '';}
  if(isset($offre['dateActualisation'])){$dateActualisation = $offre['dateActualisation'];}else{$dateActualisation = '';}
  if(isset($offre['lieuTravail']['libelle'])){$ville = $offre['lieuTravail']['libelle'];}else{$ville = '';}
  if(isset($offre['appellationlibelle'])){$metier = $offre['appellationlibelle'];}else{$metier = '';}
  if(isset($offre['entreprise']['nom'])){$entreprise = $offre['entreprise']['nom'];}else{$entreprise = '';}
  if(isset($offre['typeContratLibelle'])){$contrat = $offre['typeContratLibelle'];}else{$contrat = '';}
  if(isset($offre['natureContrat'])){$natureContrat = $offre['natureContrat'];}else{$natureContrat = '';}
  if(isset($offre['experienceLibelle'])){$experience = $offre['experienceLibelle'];}else{$experience = '';}
  if(isset($offre['salaire']['libelle'])){$salaire = $offre['salaire']['libelle'];}else{$salaire = '';}
  if(isset($offre['description'])){$description = nl2br($offre['description']); }else{$description = '';}
  if(isset($offre['origineOffre']['urlOrigine'])){$url = $offre['origineOffre']['urlOrigine']; }else{$url = 'https://candidat.pole-emploi.fr/offres/recherche/detail/' . $offre['id'];}
  if(isset($offre['dureeTravailLibelle'])){$dureeTravail = $offre['dureeTravailLibelle']; }else{$dureeTravail  = '';}
  if(isset($offre['lieuTravail']['latitude']) && isset($offre['lieuTravail']['longitude']))
  {
    $latitude = $offre['lieuTravail']['latitude'];
    $longitude = $offre['lieuTravail']['longitude'];
  }
  else
  {
    $latitude = '';
    $longitude = '';    
  }
  


  return $offer = array(
    'id' => $offre['id'],
    'intitule' => $intitule,
    'dateCreation' => $dateCreation,
    'dateActualisation' => $dateActualisation,
    'ville' => $ville,
    'metier' => $metier,
    'entreprise' => $entreprise,
    'contrat' => $contrat,
    'natureContrat' => $natureContrat,
    'experience' => $experience,
    'salaire' => $salaire,
    'description' => $description,
    'lien_pe' => $url,
    'latitude' => $latitude,
    'longitude' => $longitude,
  );

}


/**
* Page d'affichage du résultat de la recherche
*/
function api_emploi_result() {

  if(isset($_GET['ville'])){$ville = $_GET['ville'];}else{$ville = 0;}
  if(isset($_GET['grandDomaine'])){$domaine = $_GET['grandDomaine'];}else{$domaine = '0';}
  if(isset($_GET['sort'])){$sort = $_GET['sort'];}else{$sort = 1;}
  if(isset($_GET['distance'])){$distance = $_GET['distance'];}else{$distance = 4;}
  if(isset($_GET['typeContrat'])){$typeContrat = $_GET['typeContrat'];}else{$typeContrat = 0;}
  if(isset($_GET['tempsPlein'])){$tempsPlein = $_GET['tempsPlein'];}else{$tempsPlein = 'X';}
  if(isset($_GET['experience'])){$experience = $_GET['experience'];}else{$experience = 0;}
  if(isset($_GET['qualification'])){$qualification = $_GET['qualification'];}else{$qualification = 1;}
  if(isset($_GET['publieeDepuis'])){$publieeDepuis = $_GET['publieeDepuis'];}else{$publieeDepuis = 0;}

  $url = url_request_creator($ville, $domaine, $sort, $distance, $typeContrat, $tempsPlein, $experience, $qualification, $publieeDepuis);  
  if(isset($_GET['page'])){$page = $_GET['page'];}else{$page=0;}
  $request = getoffers($url, $page);

  if(!empty($request['offres']))
  {
    
    if(!empty($request)){
      $content['nombre'] = compter_emploi_ville($request);
    }
    else{
      $content['nombre'] = 0;
    }
    return theme_api_emploi_paragraph($request);
  }
  else{
    return not_found();
  }



  ;
}


/*
 * url : /api_emploi
 * Page de base : Les offres d'emploi dans la métropole de Montpellier
 * Récupération des offres des plus grandes communes de la metropole (5 communes max par requete)
 */
function api_emploi_content() {
 
  $request = getoffers(url_request_creator()); //offres de montpellier par defaut

   return theme_api_emploi_paragraph($request);
}

function api_emploi_saisonnier() {

  $request = getoffers(url_request_creator(
    $ville = 0, 
    $domaine = '0', 
    $sort = 1,
    $distance = 15, 
    $typeContrat = 'SAI', 
    $tempsPlein = 'X', 
    $experience = 0, 
    $qualification = 1, 
    $publieeDepuis = 0
  ));
  return theme_api_emploi_paragraph($request);
}

function api_emploi_formation(){
  $request = getoffers(url_request_creator(
    $ville = 0, 
    $domaine = '0', 
    $sort = 1,
    $distance = 15, 
    $typeContrat = 'forma', 
    $tempsPlein = 'X', 
    $experience = 0, 
    $qualification = 1, 
    $publieeDepuis = 0
  ));
  return theme_api_emploi_paragraph($request);
}




/*
 * url : Création des pages de navigations dans les offres d'emplois
 */
function api_navigation($parameters) {


  $nombre = 30;
  $total = ceil($parameters['nombre_offres'] / $nombre);

  $navigation = array();
  $init = 0;

  $nav = $parameters['base_url'];


    $nav .= '?ville=' . $parameters['ville'];
    $nav .= '&grandDomaine=' . $parameters['domaine'];
    $nav .= '&sort=' . $parameters['sort'];
    $nav .= '&distance=' . $parameters['distance'];
    $nav .= '&typeContrat=' . $parameters['typeContrat'];
    $nav .= '&tempsPlein=' . $parameters['tempsPlein'];
    $nav .= '&experience=' . $parameters['experience'];
    $nav .= '&qualification=' . $parameters['qualification'];
    $nav .= '&publieeDepuis=' . $parameters['publieeDepuis'];



  while($init < $total and $init < 34)
  {  
    $nav_url = $nav . '&page=' . $init;
    $init++;
    array_push($navigation, $nav_url);
  }


   return $navigation;
}


function api_emploi_one() {

 $url = 'https://api.emploi-store.fr/partenaire/offresdemploi/v2/offres/' . $_GET['id'];
 $extract = extractOffer(extract_Json($url));

  return theme_api_emploi_one($extract);
}

 /**
 * Affichage du resultat de la requete en liste
 */
function not_found() {

  $output = "<p>Il n'y a aucune offre correspondant à ces critères. </p>";

  return $output;
}


function api_emploi_total() {

  $total = get_total_offres_metropole();

  return $total;
}

function url_creator(){

  $url ='';


  if(current_path() == 'offre-emploi'){
    $url .='?id=' . $_GET['id'];
  }

  if(isset($_GET['page'])){ $url .= '&page=' . $_GET['page']; }else{$url .= '&page=0';}
  if(isset($_GET['ville'])){ $url .= '&ville=' . $_GET['ville']; }
  if(isset($_GET['grandDomaine'])){ $url .= '&grandDomaine=' . $_GET['grandDomaine']; }
  if(isset($_GET['sort'])){ $url .= '&sort=' . $_GET['sort'];}
  if(isset($_GET['distance'])){ $url .= '&distance=' . $_GET['distance']; }
  if(isset($_GET['typeContrat'])){ $url .= '&typeContrat=' . $_GET['typeContrat']; }
  if(isset($_GET['experience'])){ $url .= '&experience=' . $_GET['experience']; }
  if(isset($_GET['qualification'])){ $url .= '&qualification=' . $_GET['qualification']; }
  if(isset($_GET['publieeDepuis'])){ $url .= '&publieeDepuis=' . $_GET['publieeDepuis']; }
  $url .= '&base_url=' . current_path();
  return $url;

}


 /**
 * Formatage des offres en div
 */
function convert_div($o){

  $description = substr($o['description'],0,150);

  $url = url_creator();

  $pre_date = date_create($o['dateCreation']);
  $date = date_format($pre_date, 'd-m-Y');


  $output = '<div class="offre">';
  
  $output .= '<h2 class="offre_titre">'.$o['intitule'].'</h2>';


  if(!empty($o['entreprise'])){
    $output .= '<h3 class="offre_entreprise">'.$o['entreprise'].'</h4>';
  }

  
  $output .= '<ul class="offre_details">';
  $output .= '<li class="offre_ville">Ville : '.$o['ville'].'</li>';
  $output .= '<li class="offre_date">Annonce '. $date .'</li>';
  $output .= '<li class="offre_contrat">'.$o['natureContrat'].' - '.$o['contrat']. '- 2 Mois</li>';
  
  
  
  $output .= '</ul>';
  
  $output .= '<p class="offre_description">' . $description . '(...)</p>';
  
  $output .= '<a class="offre_lien" href="offre-emploi?id=' . $o['id'] . $url .'">Voir l\'offre</a>';
  
  $output .= '</div>';

  $output .= '<hr />';



  return $output;
}

/**
* Nombre d'offre pour une ville
*/
function compter_emploi_ville($extract){
  $total = 0;
  foreach($extract as $e){
    if(isset($e['nbResultats'])){
      $total = $total + $e['nbResultats'];
    }
  }
  return $total;
}

/**
* Calcul du nombre total d'offre d'emploi sur la metropole
*/
function get_total_offres_metropole(){

  $villes = liste_ville();


  $total = 0;
  foreach($villes as $k=>$v){
    $url = array();
    $url = variable_get('api_emploi_module_url') . "&commune=" . $k . "&distance=0&range=0-1";

    $extract = extract_Json($url);

    if(!empty($extract['filtresPossibles'])){
      $total_ville = compter_emploi_ville($extract['filtresPossibles'][0]['agregation']);
      $total = $total + $total_ville;
    }
  }

  return $total; 
}

/**
 * PARTIE TEMPLATE
 */

/**
 * Implementation of hook_theme
 */
function one_theme () {
  $functions = array(
    'one_offer' => array (
      'variables' => array('title' => NULL, 'content' => NULL)
    )
  );
  return $functions;
}

/**
 * Fonction de thème par défaut
 */
function theme_one_offer($variables) {
  $output = '<h4>'.$variable['title'].'</h4>';
  $output .= '<p>'.$variable['content'].'</p>';
  return $output;
}


/**
 * Affichage du resultat de la requete de toutes les offres de la metropole
 */
function theme_api_emploi_paragraph($variables) {

  if(!empty($variables['offres']))
  { 
    $output = '';

    if($variables['parameters']['base_url'] == 'offres-emploi-saisonnier'){
      $output .=  '<h3>Nombre d\'offres d\'emplois saisonnier sur la métropole : <b>' . $variables['parameters']['nombre_offres'] . '</b></h3>';
    }

    if($variables['parameters']['base_url'] == 'offres-alternance'){
      $output .=  '<h3>Nombre d\'offres de formations et d\'alternances sur la métropole : <b>' . $variables['parameters']['nombre_offres'] . '</b></h3>';
    }



    if($variables['parameters']['base_url'] == 'offres-emploi'){
      if($variables['parameters']['ville'] != 0){
        $req_ville = $variables['libelle_ville'];
      }
      else
      {
        $req_ville = 'metropole de Montpellier';
      }

     
        $liste_domaines = liste_domaines();
        $liste_distance = liste_distance();
        $liste_tri = liste_tri();
        $liste_contrat = liste_contrat();

        if($variables['parameters']['tempsPlein'] == 1){ $req_tempsPlein = 'Temps Plein'; }
        elseif($variables['parameters']['tempsPlein'] == 0){$req_tempsPlein = 'Temps Partiel';}
        elseif($variables['parameters']['tempsPlein'] == "X"){$req_tempsPlein = '';}
        
        $liste_experience = liste_experience();
        $liste_qualification = liste_qualification();


        if(isset($_GET['ville']) and $_GET['ville'] != 0){
          $output .=  '<h1 class="titre_resultat">Résultat de votre recherche : </h1>';
          $output .=  '<p class="nombre_reponses">Nombre d\'offre correspondant à votre recherche : Résultat : <b>' . $variables['parameters']['nombre_offres'] . '</b></p>';
        }




    }

  if($variables['parameters']['nombre_offres'] > 30){
        $output .= pagination($variables);
      }

      foreach($variables['offres'] as $o){
          $output .= convert_div($o);
      }

      $output .= pagination($variables);
      

    }
  else{
      $output = "Aucune offre dans ces critères";
    }


  return $output;
}

function pagination($variables){

  if(isset($_GET['page'])){
    $page = $_GET['page'];
  }
  else{
    $page = 0;
  }


  $output = '';

    $output .= '<ul class="ul_pagination">';
    $i = 0;
    foreach($variables['pagination'] as $p){
      $output .= '<li  class="li_pagination" style="display: inline;"><a href="'.$p .'"> ';
      if($i == $page){ $output .= ' <b class="active_pagination">';  }
      $output .= $i;
      if($i == $page){ $output .= ' </b>';  }
      $output .= ' </a></li>';
      $i++;
    }
    $output .= '</ul>'; 

    return $output;
}


 /**
 * Affichage d'une offre
 */
function theme_api_emploi_one($offre)
{

dpm($offre);
  $url = $_GET['base_url'] . url_creator();
  $token = getapitoken(token_url_creator());

  $output = '<h1  class=""emploi_intitule">' . $offre['intitule'] . '</h1>';
  if(!empty($offre['entreprise']))
  {
    $output .= '<h2 class="emploi_entreprise">Entreprise : ' . $offre['entreprise'] .  '</h2>';
  }

  if(!empty($offre['metier'])){
    $output .= '<h3 class="emploi_metier">' . $offre['metier'] .  '</h3>';

  }

  $output .= '<ul class="emploi_ul">';
  $date = date_create($offre['dateActualisation']);
  $output .= '<li class=""emploi_li_date">Date de l\'annonce : ' . date_format($date, 'd-m-Y') . '</li>';

  if(!empty($offre['ville']))
  {
  $output .= '<li class=""emploi_li_ville"> Lieu de travail : ' . $offre['ville'] . '</li>';
  }


  if(!empty($offre['contrat'])){
  $output .= '<li class=""emploi_li_contrat">Type de contrat : ' . $offre['natureContrat'] . ' / '  .$offre['contrat'] .'</li>';  
  }

  if(!empty($offre['dureeTravailLibelle'])){
    $output .= '<li class=""emploi_li_duree">Durée de travail : ' . $offre['dureeTravailLibelle'] . '</li>';
  }

  if(!empty($offre['experience'])){
    $output .= '<li class=""emploi_li_experience">Experience requise : ' . $offre['experience'] . '</li>';
  }

  if(!empty($offre['salaire'])){
    $output .= '<li class=""emploi_li_salaire">Salaire : ' . $offre['salaire'] . '</li>';
  }

  $output .= '</ul>';
  $output .= '<a  class=""emploi_lien" href="' . $url . '">Retour</a> | ';
  $output .= '<a  class=""emploi_lien_pole_emploi" href="' . $offre['lien_pe'] . '" target="_blank">Postulez sur le site de Pôle Emploi</a>';
  $output .= '<hr />';

  $output .= '<p class=""emploi_description">' . $offre['description'] .'</p>';
  $output .= '<hr />';

  // AFFICHAGE DE LA CARTE GOOGLE MAP (attention API KEY propriétaire)
  if(!empty($offre['latitude']) && !empty($offre['longitude']))
  {
    $output .= '<iframe ';
    $output .=   'width="600"';
    $output .=   'height="400"';
    $output .=   'frameborder="0" style="border:0"';
    $output .=   'src="https://www.google.com/maps/embed/v1/place?key=AIzaSyB0X4kJMOTDHqCa9MJ6zSBTBJNET0opM4w';
    $output .=  '&center=' . $offre['latitude'] .  ',' . $offre['longitude'];
    $output .=  '&zoom=12';
    $output .=  '&q=' . $offre['ville'];
    $output .= '" allowfullscreen>';
    $output .= '</iframe>';
  }



  return $output;
}











